### PR TITLE
feat: add option to provide a config file path, update default conf l…

### PR DESCRIPTION
**Pull request by sanjayankur31**
…ocations

If `-c <path>` is provided, it will look there first. If not provided, or if it could not read the file at the provided path, it will look at the default locations: `~/.nsgrest.conf` and `~/nsgrest.conf` (without a dot) in order.

### CODE REVIEW

**Comment by sanjayankur31** [comment]
CI works fine in my fork here: https://github.com/sanjayankur31/pynsgr/pull/2

Secrets etc. need updating here? (although they did seem to be working before?)

**Comment by sanjayankur31** [comment]
Managed to figure out the windows bits too, so tests pass on all OSes now:

https://github.com/sanjayankur31/pynsgr/actions/runs/6108882058

I think we need to set the secrets in this repo to get this to work properly (or make sure the script is using the correct env vars and so on).

**Comment by pgleeson** [comment]
FYI looks like it only runs with secrets when it starts from a commit to the main repo, not for prs...

BTW, shouldn't the usage info be something like 
```
  nsgr_job OPTIONS

    Where OPTIONS are:

    -h
        help

    -c path_to_config_file
        path to config file

```
i.e. show -c needs a filepath?

**Comment by sanjayankur31** [comment]
Ah, yeh, it should have that. I'll add that in.

**Pull request merged**
